version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  setup_buildx:
    environment:
      BUILDX_VERSION: v0.12.0
    docker:
      - image: cimg/python:3.12.1
    steps:
      - run:
          name: Installing Docker buildx
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker version
            apk add --no-cache curl jq python3 py3-pip
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent --show-error --location --fail --retry 3 --output /tmp/docker-buildx \
            "https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64"
            mv /tmp/docker-buildx ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            docker buildx create --use
  build_and_push:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/cicd:testeagr --push .

workflows:
  build_and_push-workflow:
    jobs:
      - setup_buildx
      - build_and_push:
          requires:
            - setup_buildx


# version: 2.1

# executors:
#   amd64-executor:
#     docker:
#       - image: cimg/python:3.12
#     resource_class: large

#   arm64-executor:
#     machine:
#       image: ubuntu-2204:2023.10.1
#     resource_class: arm.large

# jobs:
#   build_amd64:
#     executor: amd64-executor
#     steps:
#       - setup_remote_docker:
#           version: 20.10.14
#           docker_layer_caching: true
#       - checkout
#       - run:
#           name: Build Docker image
#           command: |
#             docker build -t $DOCKERHUB_USERNAME/cicd:testeagr .

#   build_arm64:
#     executor: arm64-executor
#     steps:
#       - checkout
#       - run:
#           name: Build Docker image
#           command: |
#             docker build -t $DOCKERHUB_USERNAME/cicd:testeagr .

#   push:
#     executor: amd64-executor
#     steps:
#       - run:
#           name: Push Docker image
#           command: |
#             echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
#             docker push $DOCKERHUB_USERNAME/cicd:testeagr

# workflows:
#   build_and_push:
#     jobs:
#       - build_amd64
#       - build_arm64
#       - push:
#           requires:
#             - build_amd64
#             - build_arm64