# version: 2.1

# orbs:
#   docker: circleci/docker@2.4.0
  
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: $DOCKERHUB_USERNAME/cicd
#           tag: circleci1,circleci2
#           docker-password: $DOCKERHUB_PASSWORD
#           docker-username: $DOCKERHUB_USERNAME


version: 2.1

orbs:
  docker: circleci/docker@2.4.0

executors:
  machine:
    docker:
      - image: docker:stable
    resource_class: large

workflows:
  build-docker-image-with-buildkit:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/cicd
          tag: circleci1,circleci2
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true