# version: 2.1

# orbs:
#   docker: circleci/docker@2.4.0
  
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: $DOCKERHUB_USERNAME/cicd
#           tag: circleci1,circleci2
#           docker-password: $DOCKERHUB_PASSWORD
#           docker-username: $DOCKERHUB_USERNAME


version: 2.1

orbs:
  docker: circleci/docker@2.4.0

executors:
  default:
    description: |
      The circleci-cli Docker image, which includes the CircleCI CLI executable.
    docker:
      - image: circleci/circleci-cli:<< parameters.tag >>
    parameters:
      resource_class:
        default: large
        description: Configure the executor resource class
        enum:
          - large
        type: enum
      tag:
        default: 0.1.26646
        description: >
          What version of the CircleCI CLI Docker image? For full list, see
          https://hub.docker.com/r/circleci/circleci-cli/tags
        type: string
    resource_class: large
    
  python:
    description: >
      An Ubuntu based image built by CircleCI with CI/CD in mind. This image
      contains basic tools and the Python runtime.
    docker:
      - image: cimg/python:<< parameters.tag >>
    parameters:
      resource_class:
        default: large
        description: Configure the executor resource class
        enum:
          - large
        type: enum
      tag:
        default: '3.11'
        description: >
          What version of the cimg/python image? For full list, see
          https://circleci.com/developer/images/image/cimg/python
        type: string
    resource_class: large

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/cicd
          tag: circleci1,circleci2
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME
          update-description: true
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/cicd
          tag: circleci1,circleci2
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true