version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2023.12
    resource_class: large

commands:
  setup:
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: false
      - run:
          name: Install qemu-user-static
          command: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - run:
          name: Verify qemu-user-static installation
          command: qemu-x86_64-static --version
      # - run:
      #     name: Setup Qemu
      #     command: |
      #       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build

jobs:
  build:
    executor: docker-executor
    resource_class: arm.large
    environment:
      IMAGE_NAME: igorferreir4/cicd
      IMAGE_TAGS: latest
      IMAGE_ARCHS: linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7
      CACHE_REPO: igorferreir4/buildcaches
      CACHE_NAME: registrator
    steps: 
      - setup
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      # - run:
      #     name: Pull Docker image for caching
      #     command: |
      #       docker pull $IMAGE_NAME || true
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            BUILDX_ARGS=""
            for tag in $(echo $IMAGE_TAGS | tr "," " "); do
              BUILDX_ARGS="$BUILDX_ARGS -t $IMAGE_NAME:$tag"
            done
            docker buildx build --cache-from=type=registry,ref=$CACHE_REPO:$CACHE_NAME-amd64 --cache-from=type=registry,ref=$CACHE_REPO:$CACHE_NAME-arm64 --push --platform $IMAGE_ARCHS $BUILDX_ARGS .
      - run:
          name: Build cache for amd64 image and push
          command: |
            docker buildx build --cache-from=type=registry,ref=$CACHE_REPO:$CACHE_NAME-amd64 --cache-to=type=registry,ref=$CACHE_REPO:$CACHE_NAME-amd64 --platform linux/amd64 .
      # - run:
      #     name: Build cache for arm64 image and push
      #     command: |
      #       docker buildx build --cache-from=type=registry,ref=$CACHE_REPO:$CACHE_NAME-arm64 --cache-to=type=registry,ref=$CACHE_REPO:$CACHE_NAME-arm64 --platform linux/arm64 .

workflows:
  build-and-push-multi-arch-image:
    jobs:
      - build