# version: 2.1

# orbs:
#   docker: circleci/docker@2.4.0
  
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: $DOCKERHUB_USERNAME/cicd
#           tag: circleci1,circleci2
#           docker-password: $DOCKERHUB_PASSWORD
#           docker-username: $DOCKERHUB_USERNAME


version: 2.1

orbs:
  docker: circleci/docker@2.4.0

executors:
  machine:
    machine:
      docker_layer_caching: false
      image: ubuntu-2204:2023.10.1
    resource_class: large
  machine-arm64:
    machine:
      docker_layer_caching: false
      image: ubuntu-2204:2023.10.1
    resource_class: arm.large

workflows:
  build-amd64:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/cicd
          tag: circleci1,circleci2
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          executor:
            name: machine
  build-arm64:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/cicd
          tag: circleci1,circleci2
          dockerfile: Dockerfile.arm64
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          executor:
            name: machine-arm64