# version: 2.1

# orbs:
#   docker: circleci/docker@2.4.0
  
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: $DOCKERHUB_USERNAME/cicd
#           tag: circleci1,circleci2
#           docker-password: $DOCKERHUB_PASSWORD
#           docker-username: $DOCKERHUB_USERNAME


version: 2.1

orbs:
  docker: circleci/docker@2.4.0

executors:
  docker:
    description: |
      The docker container to use when running this orb's jobs
    docker:
      - image: <<parameters.image>>:<<parameters.tag>>
    parameters:
      image:
        default: cimg/python
        description: Docker image name
        type: string
      tag:
        default: '3.6'
        description: Image tag
        type: string

  machine:
    description: >
      CircleCI's Ubuntu-based machine executor VM:
      https://circleci.com/docs/2.0/executor-types/#using-machine
    machine:
      docker_layer_caching: <<parameters.dlc>>
      image: <<parameters.image>>
    parameters:
      dlc:
        default: false
        description: Enable Docker Layer Caching?
        type: boolean
      image:
        default: ubuntu-2204:2023.10.1
        type: string
      resource-class:
        default: medium
        description: Resource class.
        enum:
          - medium
          - large
          - xlarge
          - 2xlarge
          - arm.medium
          - arm.large
          - arm.xlarge
          - arm.2xlarge
        type: enum
    resource_class: large

workflows:
  build-docker-image-with-buildkit:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/cicd
          tag: circleci1,circleci2
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true