version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2023.12
    resource_class: large

commands:
  setup:
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build

jobs:
  build:
    executor: docker-executor
    environment:
      IMAGE_NAME: igorferreir4/cicd
      IMAGE_TAGS: tagteste1,tagteste2
    steps: 
      - setup
      - run:
          name: Login to image registry
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            BUILDX_ARGS=""
            for tag in $(echo $IMAGE_TAGS | tr "," " "); do
              BUILDX_ARGS="$BUILDX_ARGS -t $IMAGE_NAME:$tag"
            done
            docker buildx build --push --platform linux/arm64,linux/amd64 $BUILDX_ARGS .

  build2:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: large
    environment:
      IMAGE_NAME: igorferreir4/cicd
      IMAGE_TAGS: tagteste3,tagteste4
    steps: 
      - checkout
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged hectorm/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
      - run:
          name: Login to image registry
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            BUILDX_ARGS=""
            for tag in $(echo $IMAGE_TAGS | tr "," " "); do
              BUILDX_ARGS="$BUILDX_ARGS -t $IMAGE_NAME:$tag"
            done
            docker buildx build --push --platform linux/arm64,linux/amd64 $BUILDX_ARGS .

  build3:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.large
    environment:
      IMAGE_NAME: igorferreir4/cicd
      IMAGE_TAGS: tagteste5,tagteste6
    steps: 
      - checkout
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged hectorm/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
      - run:
          name: Login to image registry
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            BUILDX_ARGS=""
            for tag in $(echo $IMAGE_TAGS | tr "," " "); do
              BUILDX_ARGS="$BUILDX_ARGS -t $IMAGE_NAME:$tag"
            done
            docker buildx build --push --platform linux/arm64 -f Dockerfile.arm64 $BUILDX_ARGS .

workflows:
  build-and-push-multi-arch-image:
    jobs:
      - build
      - build2
      - build3