version: 2.1

orbs:
  docker: circleci/docker@2.4.0

workflows:
  build-docker-image-amd64:
    environment:
      DOCKERHUB_REPO: cicd
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
          tag: tag27,tag28,$CIRCLE_SHA1
          dockerfile: Dockerfile
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME

  build-docker-image-arm64:
    environment:
      DOCKERHUB_REPO: cicd
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
          tag: tag27,tag28,$CIRCLE_SHA1
          dockerfile: Dockerfile.arm64
          docker-password: DOCKERHUB_PASSWORD
          docker-username: DOCKERHUB_USERNAME