version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: igorferreir4/circleci:teste2
    docker:
      - image: docker:stable

jobs:
  build-amd64:
    executor: docker-publisher
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Archive Docker image
          command: docker save --output amd64.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./amd64.tar

  build-arm64:
    executor: docker-publisher
    resource_class: arm.large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Archive Docker image
          command: docker save --output arm64.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./arm64.tar

  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker images
          command: |
            docker load --input /tmp/workspace/amd64.tar
            docker load --input /tmp/workspace/arm64.tar
      - run:
          name: Publish Docker image
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            docker push "${IMAGE_TAG}"

workflows:
  build-push:
    jobs:
      - build-amd64
      - build-arm64
      - push:
          requires:
            - build-amd64
            - build-arm64
          filters:
            branches:
              only: main