version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2023.12
    resource_class: large

commands:
  setup:
    steps:
      - checkout
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build

jobs:
  build:
    executor: docker-executor
    # machine:
    #   image: ubuntu-2204:2023.10.1
    # resource_class: arm.large
    environment:
      IMAGE_NAME: igorferreir4/cicd
      IMAGE_TAGS: tagteste1,latest
    steps:
      - setup
      - run:
          name: Login to image registry
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Pull Docker image for caching
          command: |
            docker pull $IMAGE_NAME:tagteste || true
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            IFS=',' read -ra TAGS <<< "$IMAGE_TAGS"
            docker buildx build --push --platform linux/arm64,linux/amd64 -t $IMAGE_NAME:${TAGS[0]} .
            for tag in "${TAGS[@]:1}"; do
              docker tag $IMAGE_NAME:${TAGS[0]} $IMAGE_NAME:$tag
              docker push $IMAGE_NAME:$tag
            done
            # DOCKER_CLI_EXPERIMENTAL=enabled
            # docker buildx build --push --platform linux/arm64,linux/amd64 -t $IMAGE_NAME:$IMAGE_TAGS .

workflows:
  build-and-push-multi-arch-image:
    jobs:
      - build