version: '2.1'

orbs:
  docker: circleci/docker@2.4.0

workflows:
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          remote-docker-version: docker24
          update-description: true
          use-buildkit: true
          use-remote-docker: true
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD